spring:
  profiles:
    active: prod
  datasource:
    application:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/zhoupb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    userName: root
    password: zhou1994
  jpa:

      show-sql: true